name: Publish

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Build & ZIP
        run: |
          npm install
          make zip
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: extension.zip
          extension-id: hafibifkmnaepcndbbionnhdcgkonmfj
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: true
